export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COMPANIES_SUCCESS = 'LOAD_COMPANIES_SUCCESS';
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';

// export const LOAD_ONE_COMPANY_SUCCESS = 'LOAD_ONE_COMPANY_SUCCESS';

export const LOAD_PEOPLE_SUCCESS = 'LOAD_PEOPLE_SUCCESS';
export const CREATE_PERSON_SUCCESS = 'CREATE_PERSON_SUCCESS';
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS';

export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
